version: '3.0'
services:
  hugoqrbookservice:
    build: .
    image: hugotsaodocker/hugoqrbookservice
    ports:
    - "8080:8080"
  mongo:
    image: mongo:latest
    ports:
    - "27017:27017"
    expose:
    - "27017"